[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
# Monad testnet compat
evm_version = "cancun"

[rpc_endpoints]
monad_testnet = "https://monad-testnet.drpc.org"
monad_mainnet = "https://monad-mainnet.drpc.org"
